/* XPM */
static char * 2 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"50 50 9 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	c Black",
"X	c Blue",
"o	c Cyan",
"O	c Green",
"+	c Yellow",
"@	c Red",
"#	c Magenta",
"$	c White",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"XXXXXXXX.XXXXXXXXXXooO++O+OoOOOoXXXXXXXXXXXX.XXXXX",
".XXXXXXXXXXXXXXXXXo++@@@@+@+++O+OOXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXoO+@@##@@@++++++@@@OoXXXX.XXX.XXX.",
"XXXXXXXXXXXXX.Xo+@@#@@@@+++OO++++@+@+O+oXXXXXXXXX.",
"XXXoXXXXXXXX.Xo+@@@+O+++O+++OO@@@#+@++@+X.XoXXXX.X",
"XXXXXXXXXXXXXO++@OO++O+OOOO+++@@+@@@@+@@OXXXXXXXXX",
"XXXXXXXXXXXo+++++++O++++OOO+@@@@+@@@@#@@OOX..XXXXX",
"XXXXXXXXXXoO+@+OO+++++OO+@@@@@@@@@@@@##+OOXXX.XXX.",
"XXXXXXXXXo++++O+@+++++@@@@+#@@@++@@@+@@@@+oXXXXXXX",
"XXXXXXXXo+@@++OOO++++#+@@@@##@+@@@@+@@@@@+OXXXXXXX",
"XXXX.XXo@@++O++++++@###@@@@@@@+++@++@@@++@OoXXXXXX",
"XXXXXXo@+++O+++@@####@@@@+@@@@@@@@@@@@@+@@+Oo.X..X",
"XXXXXo++@+++@#+#$#@@@@+@@@@#+@@+@#@#@+@@+++OoXXXXX",
"X..XXO@@O++##@@+#@@@@#@@@+#@++@+@++@@++@+@+OXXXXXX",
"XXXXo+#@+++#@+@@@@@@@@@@@@@@@@@@@@+@@@@++##+oXXXXX",
"XXXX+@@++@@$+@@+@#@@@@@@@@@+@@@@+@++@+@@@+#@oXXXXX",
"XXXO@@@+@@@@@@#@@++@@+@++@@@@@@++@@++@+@@@@+OoX.XX",
"X.Xo@@@++@#+@@#@+@@++@+@+@@+@@+O@+@++@+@+@+OO.XXXX",
"X.XO@#+O+@+@++@@+@@@++++@+#++++++++++++++@+oXXXX..",
"XXXO@+OO++@++++@++@++++++@+++++O+@+++++@@@oXX.XXXX",
"XXXO@+O+##@+++@+@@@+@++@@@++++OO++++@@@++OXXXX.XXX",
"XXXX@+++@@@@+@@+@@@@+++++++O++++@+++@@@@oXXXXXX..X",
"XX.XO@+@+@@@@@+++@@++++++O+++OO+@++@+@+OXXXXXXXXXX",
"XXXXXO@@@@@@@+##@@@+@++@+++++@@@+@++++oXXXXXXXXX.X",
"XXXX.oO#@@@@@@@#@@#@@@++++++++#@+++@+XXXXXXXXXXXXX",
"XXXXXXO@@+@@@@#@#@@@@@@@++@++@++O+OooXX.X.XXXXXXXX",
"X.XXXXXoO@++@@##@####@@+@@@++O++OOoXXXX.XXXXXXXXXX",
".XXXX.XXoO@@+####@@@@@@++++++OOOoXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXoO+@++@@@++++++OO+OOoXXXXXXXXXXXXXXXXXXX",
"XXXXXXX.XXXXXooOoooOOOoOooXXXXXXXXXXXX.XXXXXXXXX.X",
"XXXXX.XXXXXXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXXXXXXXX",
"XXXXXXX.XXXXXXX.XXXXXXXX.XXXXXXXXXXX.XXXX...XXXXX.",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "};
