/* XPM */
static char * 5 [] = {
/* width height ncolors cpp [x_hot y_hot] */
"50 50 9 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	c Black",
"X	c Blue",
"o	c Cyan",
"O	c Green",
"+	c Yellow",
"@	c Red",
"#	c Magenta",
"$	c White",
/* pixels */
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"XXoXXoXXXXXXXXXXoXXoOO+O+OO+OOO+oXXXXXXXXoXooooXXX",
"XXXXXXoXXXXXXXXoXoOO+++@+@+@@@+@@+ooXoXXXXXXooXoXX",
"XXXXXXXooXXXXXXooO@@#+@+@+@++++@+#++OooXXXoXXXXXoX",
"XXXXXXXoXXXXXXXo+@++++++@+++@@+@#++@+@+oXoXoXXXXXX",
"XXoXXXXXXoXXXXO++@++@@@+@@@@++@#@@+@+@#XXXoXXXXXXX",
"XXXooXXXXXXXo+@@+@@+@++@@@@@@@@@@@@#@@#O..oooXXXXX",
"XooXXXXXXXXoO@++++@O@++@+++@@@+@@@++##@@X.XXoXooXX",
"XXXXXXoooXo++++@@+@+@@@@@+@@@+@@@@@@#@@@o.XXXoXoXo",
"XXXXoXXXXo+@@@+@+++@O@@+@@@@#@@#@#@@@@@@+X..oXXoXX",
"XXXXXXXoO++@@@+++++@@#@#@#@@@@+##@@+@#@@@o..XoXooo",
"XXXXXXXO+@O@++@+@@+####@@+@#@+@+@@++#@@@++...XXoXX",
"XXXXXXO+@+++@@+@@#####@#+@@@@@#+@@@@@@@#@@X..XooXX",
"oXXXoo@@@@@@@+###@@@##@@@+#@#@@@+@#@@@@@@+o..XXooX",
"oXooo+@+@@@@@####@#@@#@@@@@#@@@@@@#$@#@@@@oXX.XoXX",
"XXXoo@+@@+@#@+#@$@#@###@#@@@@@@@@@##@#@#@+oX.XXoXX",
"oXoo++O+@@##@@#####@@@#@#@++###@@@+@@##@@#@oXXoXXX",
"XXXO++@+@@@@@@@@#@@#@+@@@+@@#@@@#@@#@@#@@@@@OXXooX",
"Xoo+@@+++#@@@@@#@@@@O@++@@+@@@@@++@@@##@@#@+OXXoXX",
"XXX+@@+++@@@@@+@@@+@@++@@@@@+@@@@@@@@+@@@++oXXXXXX",
"XXX++@++@@@@@+@+#@@+@@@@@@+@@++@@+#@@@+#+@+XXoXXXX",
"oXX++@+++@@@+@@+++@+@@@@@+@@@@@@@+@@+@@@@+XXXXXXXX",
"XXXo@+++@@#@@@++@@@#@@@@+@#++@+@@@@++++++X.XoXXXXX",
"XXoXO+++@++#@@+@@@@@@+@@@@+@@+@+@@@@@@@+oXXXXXXXoX",
"XXooo@@+@@@@#@@@@@#+++@+@@#@@+@@+$#@#@+XXoXXXXXXXX",
"oXXXXO@+@@@#@#@#@@@@+##@@#@@@#@@@@@@+OoXXXXoXXXXXX",
"XXXXoXO@@@++@@@##@##@@@@@@#@@@+@++++oXXXXoXXXXoXXX",
"XXXoXXXo@#+@@@$##@@##@@@+@@@+@@@@+OXXoXXXXXXXXXXXX",
"XXXoXoXXO@++@@@##@@@#@@+@@#@@@@+OXooXXoXXXoXXXoXXX",
"XoXXoXXXXXO+++++@@@@@+++@@++@+ooXXXXXXXoXoXXXXXoXX",
"ooXXXXXXXoXXooOOO++OOO+OOOOooXoXXXXXXXXXoXXXXoXoXX",
"oXooXXXXXXXoXXXXXXXXXXXoXoXXXXXXXXXooXXXXXXXXXXXXX",
"XXXXooXXXXXoXXXXXoXXXXXXXXXXXXXXXoXXXXXXXoXXXoXoXX",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  ",
"                                                  "};
